### PR TITLE
Go 1.10 compatibility

### PR DESCRIPTION
**Pull request by dfuentes**
Fixes build issues introduced by cgo changes in go 1.10.  Uses build constraints to still build on older go versions.

The file names are not great, but not sure what else to go with.

### CODE REVIEW

**Comment by maxtaco** [comment]
Thanks for the PR, we merged see #23.

**Comment by dfuentes** [comment]
@maxtaco The PR you merged breaks building on go version before 1.10.  You should consider doing like I did in this PR and use build constraints to maintain backwards compatibility.

**Comment by maxtaco** [comment]
Ok, shows what I get by rushing though it.

We'll put it through more careful review.

**Comment by akalin-keybase** [comment]
We had to make another PR to pull in some fixes for corefoundation.go. But thank you! Let me know if you run into problems with the current master.

**Comment by dfuentes** [comment]
Thanks for the update, will give the updated code a try

**Pull request closed without merging**
