### PR TITLE
Added method Use for existing keychains

### PR DESCRIPTION
**Pull request by c-schmidt**
Hi
I need this method. It's maybe something for your master branch.

kind regards

### CODE REVIEW

**Comment by gabriel** [comment]
You can use?
```go
func NewKeychain(path string, password string)
func NewKeychainWithPrompt(path string) (Keychain, error)
```

**Comment by c-schmidt** [comment]
Thank you for your answer. I'm relative new in Go and OSX but this functions are not working for existing keychains.

SIGTRAP: trace trap
PC=0x7fffa9a6ec08 m=0 sigcode=1
signal arrived during cgo execution

goroutine 9 [syscall, locked to thread]:
runtime.cgocall(0x4112a10, 0xc420039d18, 0x0)
	.../go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420039ce8 sp=0xc420039ca8
github.com/c-schmidt/go-keychain._Cfunc_CFRelease(0x0)
	github.com/c-schmidt/go-keychain/_obj/_cgo_gotypes.go:612 +0x41 fp=0xc420039d18 sp=0xc420039ce8
github.com/c-schmidt/go-keychain.Release.func1(0x0)
	.../Go/src/github.com/c-schmidt/go-keychain/corefoundation.go:22 +0x60 fp=0xc420039d50 sp=0xc420039d18
github.com/c-schmidt/go-keychain.Release(0x0)
	.../Go/src/github.com/c-schmidt/go-keychain/corefoundation.go:22 +0x2b fp=0xc420039d68 sp=0xc420039d50
github.com/c-schmidt/go-keychain.newKeychain(0x4163d27, 0x18, 0x41604b7, 0x8, 0x0, 0x0, 0x0, 0x41f3ae0, 0xc4200112d8)
	.../Go/src/github.com/c-schmidt/go-keychain/osx.go:163 +0x174 fp=0xc420039dd8 sp=0xc420039d68
github.com/c-schmidt/go-keychain.NewKeychain(0x4163d27, 0x18, 0x41604b7, 0x8, 0x13, 0x4163d27, 0x18, 0xc420013480)
	.../Go/src/github.com/c-schmidt/go-keychain/osx.go:136 +0x4e fp=0xc420039e30 sp=0xc420039dd8
.../.../crypto.NewStore(0x4163d27, 0x18, 0x41604b7, 0x8, 0x28)
	.../Go/src/.../.../crypto/store.go:27 +0x2e3 fp=0xc420039f20 sp=0xc420039e30
.../.../crypto.TestStoreAlreadyExists(0xc42006ec30)
	.../Go/src/.../.../crypto/store_test.go:40 +0xe6 fp=0xc420039fa8 sp=0xc420039f20
testing.tRunner(0xc42006ec30, 0x4168f10)
	.../go/src/testing/testing.go:657 +0x96 fp=0xc420039fd0 sp=0xc420039fa8
runtime.goexit()
	.../go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420039fd8 sp=0xc420039fd0
created by testing.(*T).Run
	.../go/src/testing/testing.go:697 +0x2ca

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42006e5b0, 0x416340f, 0x16, 0x4168f10, 0x4056301)
	.../go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc42006e5b0)
	.../go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc42006e5b0, 0xc420051de0)
	...go/src/testing/testing.go:657 +0x96
testing.runTests(0xc42000cb20, 0x420a960, 0x6, 0x6, 0x410af95)
	.../go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc420051f20, 0xc420051f20)
	.../go/src/testing/testing.go:822 +0xfc
main.main()
	.../.../crypto/_test/_testmain.go:52 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	.../go/src/runtime/asm_amd64.s:2197 +0x1

rax    0x7fffa9e349a8
rbx    0xc420039d18
rcx    0xc420039d18
rdx    0xc420039ca0
rdi    0x0
rsi    0x420cf40
rbp    0x7fff5fbff7f0
rsp    0x7fff5fbff7f0
r8     0xc420080340
r9     0x0
r10    0xc42001c050
r11    0xc4200112d0
r12    0x1
r13    0x132
r14    0x1310
r15    0x200
rip    0x7fffa9a6ec08
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0
exit status 2

With "Use" everything works fine. But maybe I'm doing something wrong.

**Comment by lox** [comment]
Perhaps `OpenKeychain` would be clearer?

**Comment by c-schmidt** [comment]
Yes. You are right. I have changed the name.

**Comment by gabriel** [comment]
I changed it to be `NewWithPath` since it's not really opening anything. We could later expose the openKeychainRef so probably want to keep that available.

**Comment by c-schmidt** [comment]
thx

**Pull request merged**
