### PR TITLE
Propagate metadata timestamps out of keychain (1.10 only)

### PR DESCRIPTION
**Pull request by philpennock**
Export the keychain item attributes `kSecAttrCreationDate` and `kSecAttrModificationDate` out as `CreationTimeKey` and `ModificationTimeKey` fields.

This is Go 1.10+ only because older Go's cgo type handling can't safely deal with `CFDateRef` fields.  See <https://golang.org/doc/go1.10#cgo>.

### CODE REVIEW

**Comment by akalin-keybase** [comment]
Thanks for the PR! I'll see what the deal is with older Go versions and `CFDateRef` -- I'd rather not have different behavior per version, so I'll either get it working with Go 1.9.x, or maybe it's time to drop support for older Go versions...

**Comment by philpennock** [comment]
See https://github.com/99designs/aws-vault/issues/287#issuecomment-423782191 for context

**Comment by akalin-keybase** [comment]
Apologies for the delay! I'll try to get this reviewed / merged this week.

**Comment by akalin-keybase** [comment]
Okay, I finally got back to this. I got a version of this PR working with go 1.9: https://github.com/keybase/go-keychain/pull/35 . Please let me know if that works for you!

**Comment by philpennock** [comment]
#35 seems functionally the same for Go 1.10+ with the only change being to field names.  I can update the PRs for aws-vault (https://github.com/99designs/keyring/pull/26 and https://github.com/99designs/aws-vault/pull/290 ) to use the new name, that's not a problem.  I can't sanely review the pre-1.10 stuff because I just don't know CoreFoundation that well and don't want to bang my head against checking your work against the pre-1.10 Go bugs in CF handling, types and the GC system.  As long as 1.10+ works and aws-vault builds releases with that, I'm happy. :)

Thanks!

**Comment by akalin-keybase** [comment]
Closing now that https://github.com/keybase/go-keychain/pull/35 is merged. Thanks for the PR!

**Pull request closed without merging**
